[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/"
  to = "/admission-chat/"
  status = 301

[[redirects]]
  from = "/admission-chat/*"
  to = "/admission-chat/index.html"
  status = 200
